spring:
  application:
    name: UserService

  datasource:
    url: jdbc:postgresql://localhost:5432/TrueForm_user
    username: postgres
    password: Bh@rgav2906

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
